export const opportunities = [
  // Jobs (12)
  {
    id: 'job-001',
    title: 'Software Engineer, Core Systems',
    organization: 'Google',
    type: 'job',
    domain: 'Cloud Computing',
    description: 'Join the Google Cloud core infrastructure team to design, build, and maintain large-scale distributed systems. You will work on cutting-edge technologies to optimize performance and reliability.',
    location: 'Bangalore, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹35,00,000/year',
    link: 'https://careers.google.com/jobs/results/job-001',
    skills: ['C++', 'Go', 'Distributed Systems', 'Kubernetes'],
    postedDate: '2026-07-18T10:00:00Z',
    source: 'LinkedIn',
    featured: true,
    aiSummary: 'High-paying core infrastructure role at Google for candidates strong in C++ and Distributed Systems.',
    matchScore: 92
  },
  {
    id: 'job-002',
    title: 'Machine Learning Engineer',
    organization: 'Microsoft',
    type: 'job',
    domain: 'Artificial Intelligence',
    description: 'Work on large language models and integrate AI capabilities into Microsoft 365 products. Requires strong fundamentals in deep learning and NLP.',
    location: 'Hyderabad, India',
    deadline: '2026-08-10T23:59:59Z',
    stipend: '₹32,00,000/year',
    link: 'https://careers.microsoft.com/ml-engineer',
    skills: ['Python', 'PyTorch', 'NLP', 'Transformers'],
    postedDate: '2026-07-20T08:30:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Excellent opportunity to work on cutting-edge LLMs at Microsoft.',
    matchScore: 95
  },
  {
    id: 'job-003',
    title: 'Frontend Developer',
    organization: 'Atlassian',
    type: 'job',
    domain: 'Web Development',
    description: 'Build highly interactive user interfaces for Jira and Confluence using React and GraphQL. Focus on accessibility and performance at scale.',
    location: 'Remote',
    deadline: '2026-08-05T23:59:59Z',
    stipend: '₹28,00,000/year',
    link: 'https://careers.atlassian.com/frontend',
    skills: ['React', 'TypeScript', 'GraphQL', 'CSS'],
    postedDate: '2026-07-15T09:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Remote frontend role focusing on React and GraphQL for enterprise software.',
    matchScore: 88
  },
  {
    id: 'job-004',
    title: 'Cybersecurity Analyst',
    organization: 'CrowdStrike',
    type: 'job',
    domain: 'Cybersecurity',
    description: 'Monitor threat landscapes and analyze malware. You will be responsible for identifying vulnerabilities and enhancing our security posture.',
    location: 'Pune, India',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '₹22,00,000/year',
    link: 'https://crowdstrike.com/careers/analyst',
    skills: ['Network Security', 'Python', 'SIEM', 'Malware Analysis'],
    postedDate: '2026-07-19T14:15:00Z',
    source: 'Indeed',
    featured: false,
    aiSummary: 'Core cybersecurity role involving threat monitoring and malware analysis.',
    matchScore: 74
  },
  {
    id: 'job-005',
    title: 'Data Scientist',
    organization: 'Amazon',
    type: 'job',
    domain: 'Data Science',
    description: 'Leverage massive datasets to build predictive models for supply chain optimization. Experience with big data frameworks is a plus.',
    location: 'Bangalore, India',
    deadline: '2026-08-25T23:59:59Z',
    stipend: '₹30,00,000/year',
    link: 'https://amazon.jobs/data-scientist',
    skills: ['Python', 'SQL', 'Machine Learning', 'Spark'],
    postedDate: '2026-07-21T11:00:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Data Science position optimizing Amazon supply chain using ML and big data.',
    matchScore: 89
  },
  {
    id: 'job-006',
    title: 'Blockchain Developer',
    organization: 'Polygon Labs',
    type: 'job',
    domain: 'Blockchain',
    description: 'Develop and audit smart contracts for the Polygon ecosystem. Contribute to scaling solutions for Ethereum.',
    location: 'Remote',
    deadline: '2026-09-01T23:59:59Z',
    stipend: '$120,000/year',
    link: 'https://polygon.technology/careers',
    skills: ['Solidity', 'Rust', 'Web3.js', 'Cryptography'],
    postedDate: '2026-07-14T16:45:00Z',
    source: 'AngelList',
    featured: false,
    aiSummary: 'High-paying remote Web3 role focusing on smart contract development in Solidity/Rust.',
    matchScore: 68
  },
  {
    id: 'job-007',
    title: 'DevOps Engineer',
    organization: 'Netflix',
    type: 'job',
    domain: 'DevOps',
    description: 'Ensure the reliability of Netflix streaming services by building robust CI/CD pipelines and managing AWS infrastructure.',
    location: 'Los Gatos, USA (Remote possible)',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '$160,000/year',
    link: 'https://jobs.netflix.com/devops',
    skills: ['AWS', 'Terraform', 'Docker', 'Jenkins'],
    postedDate: '2026-07-20T10:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Elite DevOps role at Netflix managing critical AWS infrastructure.',
    matchScore: 78
  },
  {
    id: 'job-008',
    title: 'IoT Solutions Architect',
    organization: 'Siemens',
    type: 'job',
    domain: 'IoT',
    description: 'Design end-to-end IoT solutions for industrial automation. Work closely with hardware and software teams to deliver smart factory solutions.',
    location: 'Munich, Germany',
    deadline: '2026-09-10T23:59:59Z',
    stipend: '€85,000/year',
    link: 'https://jobs.siemens.com/iot-architect',
    skills: ['IoT', 'Edge Computing', 'C++', 'MQTT'],
    postedDate: '2026-07-12T09:30:00Z',
    source: 'Indeed',
    featured: false,
    aiSummary: 'Industrial IoT architect role in Germany for smart factory solutions.',
    matchScore: 65
  },
  {
    id: 'job-009',
    title: 'Full Stack Engineer',
    organization: 'Stripe',
    type: 'job',
    domain: 'Web Development',
    description: 'Build seamless payment experiences. Work across the stack with Ruby, React, and robust API design.',
    location: 'Remote',
    deadline: '2026-08-12T23:59:59Z',
    stipend: '$140,000/year',
    link: 'https://stripe.com/jobs/full-stack',
    skills: ['React', 'Ruby on Rails', 'API Design', 'PostgreSQL'],
    postedDate: '2026-07-21T07:00:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Top-tier remote full-stack role at Stripe requiring React and API design skills.',
    matchScore: 85
  },
  {
    id: 'job-010',
    title: 'Mobile App Developer',
    organization: 'Uber',
    type: 'job',
    domain: 'Mobile Development',
    description: 'Develop and maintain the Uber rider app. Focus on performance, offline capabilities, and complex UI animations.',
    location: 'San Francisco, USA',
    deadline: '2026-08-22T23:59:59Z',
    stipend: '$150,000/year',
    link: 'https://uber.com/careers/mobile',
    skills: ['Swift', 'Kotlin', 'React Native', 'Mobile UI'],
    postedDate: '2026-07-16T11:20:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Core mobile engineering role at Uber focusing on the rider experience.',
    matchScore: 72
  },
  {
    id: 'job-011',
    title: 'Robotics Software Engineer',
    organization: 'Boston Dynamics',
    type: 'job',
    domain: 'Robotics',
    description: 'Write control software for advanced bipedal and quadrupedal robots. Requires deep knowledge of kinematics and real-time systems.',
    location: 'Waltham, USA',
    deadline: '2026-09-05T23:59:59Z',
    stipend: '$130,000/year',
    link: 'https://bostondynamics.com/careers/robotics',
    skills: ['C++', 'ROS', 'Kinematics', 'Control Theory'],
    postedDate: '2026-07-13T14:00:00Z',
    source: 'Direct',
    featured: false,
    aiSummary: 'Exciting robotics software role working on world-class legged robots.',
    matchScore: 61
  },
  {
    id: 'job-012',
    title: 'Data Engineer',
    organization: 'Snowflake',
    type: 'job',
    domain: 'Data Science',
    description: 'Build scalable data pipelines and optimize data warehousing solutions for enterprise clients.',
    location: 'Hybrid - Mumbai',
    deadline: '2026-08-18T23:59:59Z',
    stipend: '₹26,00,000/year',
    link: 'https://careers.snowflake.com/data-engineer',
    skills: ['SQL', 'Python', 'Airflow', 'Snowflake'],
    postedDate: '2026-07-22T09:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Data engineering role focusing on scalable pipelines and data warehousing.',
    matchScore: 81
  },

  // Internships (12)
  {
    id: 'int-001',
    title: 'Software Engineering Intern',
    organization: 'Meta',
    type: 'internship',
    domain: 'Web Development',
    description: '12-week summer internship. Work on high-impact projects in React and PHP, mentored by senior engineers.',
    location: 'London, UK',
    deadline: '2026-10-01T23:59:59Z',
    stipend: '£4,500/month',
    link: 'https://metacareers.com/internships',
    skills: ['React', 'JavaScript', 'Data Structures', 'Algorithms'],
    postedDate: '2026-07-21T10:00:00Z',
    source: 'University Portal',
    featured: true,
    aiSummary: 'Prestigious Meta software engineering summer internship in London.',
    matchScore: 91
  },
  {
    id: 'int-002',
    title: 'AI Research Intern',
    organization: 'OpenAI',
    type: 'internship',
    domain: 'Artificial Intelligence',
    description: 'Assist in training and evaluating generative models. Publish findings and contribute to open-source tools.',
    location: 'San Francisco, USA',
    deadline: '2026-09-15T23:59:59Z',
    stipend: '$8,000/month',
    link: 'https://openai.com/careers/intern-ai',
    skills: ['Python', 'PyTorch', 'Deep Learning', 'Research'],
    postedDate: '2026-07-20T12:00:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Highly competitive AI research internship at OpenAI for deep learning enthusiasts.',
    matchScore: 96
  },
  {
    id: 'int-003',
    title: 'Cloud Support Intern',
    organization: 'Amazon Web Services (AWS)',
    type: 'internship',
    domain: 'Cloud Computing',
    description: 'Learn to troubleshoot and resolve complex technical issues for AWS enterprise customers.',
    location: 'Bangalore, India',
    deadline: '2026-08-10T23:59:59Z',
    stipend: '₹50,000/month',
    link: 'https://amazon.jobs/aws-intern',
    skills: ['Linux', 'Networking', 'AWS', 'Python'],
    postedDate: '2026-07-15T09:30:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'AWS cloud support internship focusing on networking and Linux troubleshooting.',
    matchScore: 76
  },
  {
    id: 'int-004',
    title: 'Cybersecurity Intern',
    organization: 'Palo Alto Networks',
    type: 'internship',
    domain: 'Cybersecurity',
    description: 'Get hands-on experience in penetration testing, vulnerability assessment, and security operations.',
    location: 'Remote',
    deadline: '2026-08-25T23:59:59Z',
    stipend: '$3,000/month',
    link: 'https://jobs.paloaltonetworks.com/intern',
    skills: ['Penetration Testing', 'Networking', 'Linux', 'Security Fundamentals'],
    postedDate: '2026-07-18T14:20:00Z',
    source: 'Indeed',
    featured: false,
    aiSummary: 'Remote cybersecurity internship covering pentesting and security operations.',
    matchScore: 68
  },
  {
    id: 'int-005',
    title: 'Data Science Intern',
    organization: 'Uber',
    type: 'internship',
    domain: 'Data Science',
    description: 'Analyze rider behavior and optimize pricing models using machine learning techniques.',
    location: 'Hyderabad, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹60,000/month',
    link: 'https://uber.com/internships/data',
    skills: ['Python', 'SQL', 'Machine Learning', 'Statistics'],
    postedDate: '2026-07-19T10:00:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'Data science internship at Uber focusing on pricing and predictive modeling.',
    matchScore: 87
  },
  {
    id: 'int-006',
    title: 'Web3 Developer Intern',
    organization: 'Binance',
    type: 'internship',
    domain: 'Blockchain',
    description: 'Learn and contribute to building decentralized applications and integrating crypto payment gateways.',
    location: 'Remote',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '$2,500/month',
    link: 'https://binance.com/careers/intern',
    skills: ['Solidity', 'React', 'Web3.js', 'Smart Contracts'],
    postedDate: '2026-07-17T11:00:00Z',
    source: 'AngelList',
    featured: false,
    aiSummary: 'Remote internship in Web3 development building decentralized applications.',
    matchScore: 71
  },
  {
    id: 'int-007',
    title: 'IoT Engineering Intern',
    organization: 'Bosch',
    type: 'internship',
    domain: 'IoT',
    description: 'Work on connected car technologies. Develop embedded software for vehicle-to-everything (V2X) communication.',
    location: 'Bangalore, India',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '₹40,000/month',
    link: 'https://bosch.in/careers/intern',
    skills: ['C', 'C++', 'Embedded Systems', 'IoT'],
    postedDate: '2026-07-14T09:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Embedded IoT internship at Bosch focusing on connected car technology.',
    matchScore: 65
  },
  {
    id: 'int-008',
    title: 'DevOps Intern',
    organization: 'Red Hat',
    type: 'internship',
    domain: 'DevOps',
    description: 'Assist in maintaining CI/CD pipelines and learn enterprise Kubernetes deployment strategies.',
    location: 'Pune, India',
    deadline: '2026-08-22T23:59:59Z',
    stipend: '₹45,000/month',
    link: 'https://redhat.com/jobs/intern',
    skills: ['Linux', 'Docker', 'Kubernetes', 'Bash'],
    postedDate: '2026-07-21T13:30:00Z',
    source: 'University Portal',
    featured: false,
    aiSummary: 'Great entry-level DevOps internship at Red Hat centered on Kubernetes.',
    matchScore: 73
  },
  {
    id: 'int-009',
    title: 'Mobile Development Intern',
    organization: 'Zomato',
    type: 'internship',
    domain: 'Mobile Development',
    description: 'Help build new features for the Zomato app. Optimize load times and improve UI/UX for millions of users.',
    location: 'Gurgaon, India',
    deadline: '2026-08-12T23:59:59Z',
    stipend: '₹50,000/month',
    link: 'https://zomato.com/careers',
    skills: ['React Native', 'JavaScript', 'Redux', 'UI/UX'],
    postedDate: '2026-07-16T15:00:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'React Native internship at Zomato optimizing their core consumer app.',
    matchScore: 82
  },
  {
    id: 'int-010',
    title: 'Robotics Intern',
    organization: 'GreyOrange',
    type: 'internship',
    domain: 'Robotics',
    description: 'Contribute to path planning algorithms for warehouse automation robots.',
    location: 'Noida, India',
    deadline: '2026-08-18T23:59:59Z',
    stipend: '₹35,000/month',
    link: 'https://greyorange.com/intern',
    skills: ['C++', 'Python', 'Algorithms', 'ROS'],
    postedDate: '2026-07-11T10:45:00Z',
    source: 'Indeed',
    featured: false,
    aiSummary: 'Warehouse robotics internship focusing on path planning and ROS.',
    matchScore: 66
  },
  {
    id: 'int-011',
    title: 'Backend Engineering Intern',
    organization: 'Discord',
    type: 'internship',
    domain: 'Web Development',
    description: 'Scale our messaging infrastructure. Work with Rust and Elixir to handle millions of concurrent websocket connections.',
    location: 'Remote',
    deadline: '2026-09-01T23:59:59Z',
    stipend: '$5,000/month',
    link: 'https://discord.com/jobs/intern',
    skills: ['Rust', 'Python', 'Distributed Systems', 'PostgreSQL'],
    postedDate: '2026-07-22T08:00:00Z',
    source: 'LinkedIn',
    featured: true,
    aiSummary: 'High-performance backend engineering internship at Discord using Rust.',
    matchScore: 86
  },
  {
    id: 'int-012',
    title: 'Product Management Intern (Tech)',
    organization: 'Razorpay',
    type: 'internship',
    domain: 'Web Development',
    description: 'Work alongside engineers and designers to spec and deliver new payment APIs and dashboard features.',
    location: 'Bangalore, India',
    deadline: '2026-08-05T23:59:59Z',
    stipend: '₹60,000/month',
    link: 'https://razorpay.com/jobs/intern',
    skills: ['Product Strategy', 'API Design', 'Data Analysis', 'Agile'],
    postedDate: '2026-07-19T09:15:00Z',
    source: 'Direct',
    featured: false,
    aiSummary: 'Technical PM internship at Razorpay bridging engineering and product.',
    matchScore: 70
  },

  // Hackathons (10)
  {
    id: 'hack-001',
    title: 'Smart India Hackathon 2026',
    organization: 'Govt. of India',
    type: 'hackathon',
    domain: 'Multiple Domains',
    description: 'World\'s largest open innovation model. Solve problem statements provided by various ministries and PSUs.',
    location: 'Various Nodal Centers, India',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '₹1,00,000 prize per problem',
    link: 'https://sih.gov.in',
    skills: ['Web Development', 'App Development', 'AI', 'IoT'],
    postedDate: '2026-07-15T10:00:00Z',
    source: 'Unstop',
    featured: true,
    aiSummary: 'Premier national-level hackathon with massive cash prizes and government recognition.',
    matchScore: 88
  },
  {
    id: 'hack-002',
    title: 'ETHIndia 2026',
    organization: 'Devfolio',
    type: 'hackathon',
    domain: 'Blockchain',
    description: 'Asia\'s biggest Ethereum hackathon. Build innovative Web3 dApps, protocols, and tooling over 36 hours.',
    location: 'Bangalore, India',
    deadline: '2026-11-15T23:59:59Z',
    stipend: '$50,000+ in bounties',
    link: 'https://ethindia.co',
    skills: ['Solidity', 'React', 'Ethereum', 'Smart Contracts'],
    postedDate: '2026-07-20T14:00:00Z',
    source: 'Devfolio',
    featured: true,
    aiSummary: 'Top-tier Web3 hackathon in Bangalore with huge global bounties.',
    matchScore: 72
  },
  {
    id: 'hack-003',
    title: 'GenAI Buildathon',
    organization: 'Hugging Face x Google',
    type: 'hackathon',
    domain: 'Artificial Intelligence',
    description: 'Create novel applications utilizing large language models and open-source datasets. 48 hours of intense coding.',
    location: 'Remote',
    deadline: '2026-08-25T23:59:59Z',
    stipend: '$10,000 total prize pool',
    link: 'https://huggingface.co/hackathon',
    skills: ['LLMs', 'Python', 'LangChain', 'GCP'],
    postedDate: '2026-07-21T09:00:00Z',
    source: 'Devfolio',
    featured: true,
    aiSummary: 'Remote generative AI hackathon by Hugging Face and Google. Highly relevant to your ML skills.',
    matchScore: 98
  },
  {
    id: 'hack-004',
    title: 'HackMIT 2026',
    organization: 'MIT',
    type: 'hackathon',
    domain: 'Multiple Domains',
    description: 'MIT\'s premier hackathon. Join thousands of hackers worldwide to build software and hardware projects.',
    location: 'Cambridge, USA (Hybrid)',
    deadline: '2026-09-05T23:59:59Z',
    stipend: 'Prizes & Swag',
    link: 'https://hackmit.org',
    skills: ['Full Stack', 'Hardware', 'Design', 'AI'],
    postedDate: '2026-07-10T12:00:00Z',
    source: 'Direct',
    featured: false,
    aiSummary: 'Prestigious MIT hackathon offering global networking and hybrid participation.',
    matchScore: 84
  },
  {
    id: 'hack-005',
    title: 'CyberDefenders Challenge',
    organization: 'DRDO',
    type: 'hackathon',
    domain: 'Cybersecurity',
    description: 'Solve complex cryptography puzzles, perform reverse engineering, and defend networks in a simulated environment.',
    location: 'New Delhi, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹2,50,000 prize pool',
    link: 'https://drdo.gov.in/cyber-challenge',
    skills: ['Cryptography', 'Reverse Engineering', 'Network Security'],
    postedDate: '2026-07-12T10:30:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'Government-sponsored cybersecurity challenge hosted by DRDO.',
    matchScore: 60
  },
  {
    id: 'hack-006',
    title: 'FinTech Innovation Hack',
    organization: 'NPCI',
    type: 'hackathon',
    domain: 'Web Development',
    description: 'Innovate on top of the UPI architecture. Build next-gen digital payment solutions for rural India.',
    location: 'Mumbai, India',
    deadline: '2026-09-12T23:59:59Z',
    stipend: '₹5,00,000 prize pool',
    link: 'https://npci.org.in/hackathon',
    skills: ['APIs', 'Java', 'Mobile App Dev', 'System Design'],
    postedDate: '2026-07-18T16:00:00Z',
    source: 'Devfolio',
    featured: false,
    aiSummary: 'Fintech hackathon by NPCI focused on expanding digital payments in India.',
    matchScore: 77
  },
  {
    id: 'hack-007',
    title: 'HealthTech Connect',
    organization: 'Apollo Hospitals',
    type: 'hackathon',
    domain: 'Data Science',
    description: 'Leverage anonymized patient data to build predictive models for early disease detection.',
    location: 'Remote',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '₹1,50,000 prize',
    link: 'https://apollo.com/hackathon',
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'Healthcare'],
    postedDate: '2026-07-16T09:00:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'Remote HealthTech hackathon utilizing data science for disease prediction.',
    matchScore: 89
  },
  {
    id: 'hack-008',
    title: 'Space Apps Challenge',
    organization: 'NASA x ISRO',
    type: 'hackathon',
    domain: 'Multiple Domains',
    description: 'Use open data from NASA and ISRO to solve challenges on Earth and in space. 48-hour global sprint.',
    location: 'Remote & Various Local Centers',
    deadline: '2026-10-02T23:59:59Z',
    stipend: 'Global Recognition & Swag',
    link: 'https://spaceappschallenge.org',
    skills: ['Data Visualization', 'Web Dev', 'Earth Science', 'AI'],
    postedDate: '2026-07-22T08:30:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Global space and earth science hackathon by NASA and ISRO.',
    matchScore: 85
  },
  {
    id: 'hack-009',
    title: 'Cloud Native Hackathon',
    organization: 'CNCF',
    type: 'hackathon',
    domain: 'Cloud Computing',
    description: 'Build robust cloud-native applications and open-source tooling using Kubernetes, Prometheus, and Envoy.',
    location: 'Remote',
    deadline: '2026-09-20T23:59:59Z',
    stipend: '$5,000 + CNCF Certifications',
    link: 'https://cncf.io/hackathon',
    skills: ['Go', 'Kubernetes', 'Docker', 'Microservices'],
    postedDate: '2026-07-14T11:00:00Z',
    source: 'Devfolio',
    featured: false,
    aiSummary: 'Remote cloud computing hackathon centered around CNCF projects.',
    matchScore: 74
  },
  {
    id: 'hack-010',
    title: 'IoT Smart City Hack',
    organization: 'Cisco',
    type: 'hackathon',
    domain: 'IoT',
    description: 'Develop IoT solutions for traffic management, waste management, and energy efficiency in urban environments.',
    location: 'Bangalore, India',
    deadline: '2026-08-28T23:59:59Z',
    stipend: '₹2,00,000 prize pool',
    link: 'https://cisco.com/smartcity',
    skills: ['IoT', 'Arduino', 'Raspberry Pi', 'Python'],
    postedDate: '2026-07-17T13:45:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'Smart city IoT hackathon hosted by Cisco in Bangalore.',
    matchScore: 69
  },

  // Research (8)
  {
    id: 'res-001',
    title: 'Summer Undergraduate Research Fellowship (SURF)',
    organization: 'Stanford University',
    type: 'research',
    domain: 'Artificial Intelligence',
    description: 'Work with Stanford faculty on cutting-edge AI research. Focus areas include reinforcement learning and computer vision.',
    location: 'Stanford, USA',
    deadline: '2026-12-01T23:59:59Z',
    stipend: '$6,000 stipend + housing',
    link: 'https://surf.stanford.edu',
    skills: ['Machine Learning', 'Python', 'Research', 'Mathematics'],
    postedDate: '2026-07-10T10:00:00Z',
    source: 'University Portal',
    featured: true,
    aiSummary: 'Elite undergraduate AI research fellowship at Stanford University.',
    matchScore: 97
  },
  {
    id: 'res-002',
    title: 'Research Assistant - Quantum Computing',
    organization: 'IIT Bombay',
    type: 'research',
    domain: 'Cloud Computing',
    description: 'Assist in developing quantum algorithms for cloud optimization. Requires strong linear algebra background.',
    location: 'Mumbai, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹25,000/month',
    link: 'https://iitb.ac.in/research/quantum',
    skills: ['Quantum Computing', 'Linear Algebra', 'Python', 'Qiskit'],
    postedDate: '2026-07-18T14:00:00Z',
    source: 'Direct',
    featured: false,
    aiSummary: 'Quantum computing research position at IIT Bombay focusing on cloud optimization.',
    matchScore: 64
  },
  {
    id: 'res-003',
    title: 'NLP Research Fellowship',
    organization: 'Microsoft Research',
    type: 'research',
    domain: 'Artificial Intelligence',
    description: 'Join MSR India to research low-resource language translation models. Publish papers in top-tier conferences like ACL.',
    location: 'Bangalore, India',
    deadline: '2026-09-10T23:59:59Z',
    stipend: 'Funded',
    link: 'https://research.microsoft.com/india',
    skills: ['NLP', 'Deep Learning', 'Linguistics', 'PyTorch'],
    postedDate: '2026-07-21T09:30:00Z',
    source: 'LinkedIn',
    featured: true,
    aiSummary: 'Prestigious Microsoft Research fellowship in Bangalore focused on NLP.',
    matchScore: 94
  },
  {
    id: 'res-004',
    title: 'HCI Research Assistant',
    organization: 'Carnegie Mellon University (CMU)',
    type: 'research',
    domain: 'Web Development',
    description: 'Investigate accessibility in web interfaces for visually impaired users. Conduct user studies and prototype new UI paradigms.',
    location: 'Remote',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '$2,000/month',
    link: 'https://hcii.cmu.edu/research',
    skills: ['HCI', 'JavaScript', 'Accessibility', 'UX Research'],
    postedDate: '2026-07-15T11:15:00Z',
    source: 'University Portal',
    featured: false,
    aiSummary: 'Remote Human-Computer Interaction research role with CMU.',
    matchScore: 81
  },
  {
    id: 'res-005',
    title: 'ISRO Space Tech Research Program',
    organization: 'ISRO',
    type: 'research',
    domain: 'Data Science',
    description: 'Process and analyze satellite imagery data using deep learning to monitor climate change indicators.',
    location: 'Ahmedabad, India',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '₹30,000/month',
    link: 'https://isro.gov.in/research',
    skills: ['Computer Vision', 'Python', 'Geospatial Data', 'TensorFlow'],
    postedDate: '2026-07-19T10:00:00Z',
    source: 'Direct',
    featured: false,
    aiSummary: 'Data science research at ISRO involving satellite image processing.',
    matchScore: 88
  },
  {
    id: 'res-006',
    title: 'Cyber-Physical Systems Lab Intern',
    organization: 'IISc Bangalore',
    type: 'research',
    domain: 'IoT',
    description: 'Research security vulnerabilities in industrial IoT devices. Develop lightweight encryption protocols for edge devices.',
    location: 'Bangalore, India',
    deadline: '2026-08-25T23:59:59Z',
    stipend: '₹20,000/month',
    link: 'https://iisc.ac.in/cps-lab',
    skills: ['IoT Security', 'Cryptography', 'C', 'Networking'],
    postedDate: '2026-07-16T12:00:00Z',
    source: 'Unstop',
    featured: false,
    aiSummary: 'IISc Bangalore lab internship researching IoT security and edge encryption.',
    matchScore: 67
  },
  {
    id: 'res-007',
    title: 'Blockchain Scalability Researcher',
    organization: 'Ethereum Foundation',
    type: 'research',
    domain: 'Blockchain',
    description: 'Contribute to research on Zero-Knowledge rollups and Layer 2 scalability solutions.',
    location: 'Remote',
    deadline: '2026-09-15T23:59:59Z',
    stipend: 'Grant Based ($5k - $20k)',
    link: 'https://ethereum.foundation/grants',
    skills: ['Cryptography', 'Zk-SNARKs', 'Mathematics', 'Solidity'],
    postedDate: '2026-07-20T16:30:00Z',
    source: 'AngelList',
    featured: false,
    aiSummary: 'Remote Ethereum Foundation research grant on ZK rollups.',
    matchScore: 62
  },
  {
    id: 'res-008',
    title: 'Bioinformatics Research Student',
    organization: 'Max Planck Institute',
    type: 'research',
    domain: 'Data Science',
    description: 'Apply machine learning techniques to genomic sequences to identify markers for rare genetic diseases.',
    location: 'Berlin, Germany',
    deadline: '2026-09-30T23:59:59Z',
    stipend: '€1,200/month',
    link: 'https://mpg.de/bioinformatics',
    skills: ['Bioinformatics', 'Machine Learning', 'R', 'Python'],
    postedDate: '2026-07-14T09:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Bioinformatics research role in Germany applying ML to genomic data.',
    matchScore: 79
  }
];

export const userProfile = {
  name: 'Alex Chen',
  email: 'alex.chen@university.edu',
  university: 'Indian Institute of Technology, Delhi',
  year: '3rd Year B.Tech',
  skills: ['Python', 'Machine Learning', 'React', 'Node.js', 'TensorFlow', 'SQL'],
  interests: ['Artificial Intelligence', 'Web Development', 'Data Science'],
  savedOpportunities: [],
  appliedOpportunities: []
};

export const notifications = [
  {
    id: 'notif-001',
    type: 'email',
    title: 'Application Deadline Approaching',
    message: 'Your saved opportunity "Software Engineering Intern" at Meta closes in 3 days.',
    timestamp: '2026-07-22T08:30:00Z',
    read: false,
    opportunityId: 'int-001'
  },
  {
    id: 'notif-002',
    type: 'whatsapp',
    title: 'New High-Match Job',
    message: 'We found a 95% match for you: Machine Learning Engineer at Microsoft.',
    timestamp: '2026-07-21T18:45:00Z',
    read: false,
    opportunityId: 'job-002'
  },
  {
    id: 'notif-003',
    type: 'email',
    title: 'Hackathon Registration Open',
    message: 'Smart India Hackathon 2026 registrations are now open. Form your team today!',
    timestamp: '2026-07-21T10:00:00Z',
    read: true,
    opportunityId: 'hack-001'
  },
  {
    id: 'notif-004',
    type: 'whatsapp',
    title: 'Profile View',
    message: 'A recruiter from Amazon viewed your profile for a Data Scientist role.',
    timestamp: '2026-07-20T14:20:00Z',
    read: true,
    opportunityId: 'job-005'
  },
  {
    id: 'notif-005',
    type: 'email',
    title: 'New Research Fellowship',
    message: 'Stanford SURF program just opened applications. This is a 97% match for your AI interests.',
    timestamp: '2026-07-19T09:15:00Z',
    read: false,
    opportunityId: 'res-001'
  },
  {
    id: 'notif-006',
    type: 'whatsapp',
    title: 'Interview Scheduled',
    message: 'Reminder: Your technical interview for the NLP Research Fellowship at Microsoft is tomorrow at 10 AM.',
    timestamp: '2026-07-18T16:00:00Z',
    read: true,
    opportunityId: 'res-003'
  },
  {
    id: 'notif-007',
    type: 'email',
    title: 'Weekly Roundup',
    message: 'You have 12 new matching opportunities this week. Check them out on your dashboard.',
    timestamp: '2026-07-17T08:00:00Z',
    read: true,
    opportunityId: null
  },
  {
    id: 'notif-008',
    type: 'whatsapp',
    title: 'Teammate Request',
    message: 'Rahul wants to join your team for ETHIndia 2026.',
    timestamp: '2026-07-16T19:30:00Z',
    read: true,
    opportunityId: 'hack-002'
  },
  {
    id: 'notif-009',
    type: 'email',
    title: 'Application Viewed',
    message: 'Your application for "Full Stack Engineer" at Stripe has been viewed by the hiring team.',
    timestamp: '2026-07-16T11:45:00Z',
    read: false,
    opportunityId: 'job-009'
  },
  {
    id: 'notif-010',
    type: 'whatsapp',
    title: 'Quick Tip',
    message: 'Update your portfolio link to increase your match score for Web Development roles.',
    timestamp: '2026-07-15T15:20:00Z',
    read: true,
    opportunityId: null
  },
  {
    id: 'notif-011',
    type: 'email',
    title: 'New Hackathon Matches',
    message: 'GenAI Buildathon by Hugging Face aligns perfectly with your TensorFlow skills (98% match).',
    timestamp: '2026-07-22T10:00:00Z',
    read: false,
    opportunityId: 'hack-003'
  },
  {
    id: 'notif-012',
    type: 'whatsapp',
    title: 'Stipend Update',
    message: 'The stipend for Data Science Intern at Uber has been updated to ₹60,000/month.',
    timestamp: '2026-07-18T10:30:00Z',
    read: true,
    opportunityId: 'int-005'
  },
  {
    id: 'notif-013',
    type: 'email',
    title: 'Upcoming Deadline',
    message: 'Don\'t miss out! The AWS Cloud Support Intern application closes on Aug 10.',
    timestamp: '2026-07-19T08:00:00Z',
    read: true,
    opportunityId: 'int-003'
  },
  {
    id: 'notif-014',
    type: 'whatsapp',
    title: 'Congrats!',
    message: 'Your profile has been marked as a Top 10% candidate for AI Research internships.',
    timestamp: '2026-07-21T14:10:00Z',
    read: false,
    opportunityId: null
  },
  {
    id: 'notif-015',
    type: 'email',
    title: 'New Skill Recommended',
    message: 'Learning "LangChain" could boost your match score for GenAI roles by 15%.',
    timestamp: '2026-07-20T09:00:00Z',
    read: true,
    opportunityId: null
  }
];

export const aiQuickPrompts = [
  'Find ML internships in Bangalore',
  'Show me remote Web3 hackathons',
  'Opportunities with stipends > ₹50k',
  'Research positions at top universities',
  'Match me with React roles',
  'Upcoming application deadlines this week',
  'Jobs at Google or Microsoft',
  'Hackathons with prizes above ₹1 lakh'
];

export const stats = {
  totalOpportunities: 2458,
  newToday: 142,
  deadlinesThisWeek: 37,
  avgMatchScore: 78
};
