export const opportunities = [
  // Jobs (12)
  {
    id: 'job-001',
    title: 'Software Engineer, Core Systems',
    organization: 'Google',
    type: 'job',
    domain: 'Cloud Computing',
    description: 'Join the Google Cloud core infrastructure team to design, build, and maintain large-scale distributed systems. Work on cutting-edge technologies to optimize performance and reliability across global datacenters.',
    location: 'Bangalore, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹35,00,000/year',
    link: 'https://www.google.com/about/careers/applications/jobs/results/?q=Software%20Engineer',
    skills: ['C++', 'Go', 'Distributed Systems', 'Kubernetes'],
    postedDate: '2026-07-18T10:00:00Z',
    source: 'LinkedIn',
    featured: true,
    aiSummary: 'High-paying core infrastructure role at Google for candidates strong in C++ and Distributed Systems.',
    matchScore: 92
  },
  {
    id: 'job-002',
    title: 'Machine Learning Engineer',
    organization: 'Microsoft',
    type: 'job',
    domain: 'Artificial Intelligence',
    description: 'Work on large language models and integrate AI capabilities into Microsoft 365 & Copilot products. Requires strong fundamentals in deep learning, PyTorch, and NLP.',
    location: 'Hyderabad, India',
    deadline: '2026-08-10T23:59:59Z',
    stipend: '₹32,00,000/year',
    link: 'https://jobs.careers.microsoft.com/global/en/search?q=Machine%20Learning',
    skills: ['Python', 'PyTorch', 'NLP', 'Transformers'],
    postedDate: '2026-07-20T08:30:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Excellent opportunity to work on cutting-edge LLMs at Microsoft.',
    matchScore: 95
  },
  {
    id: 'job-003',
    title: 'Frontend Developer',
    organization: 'Atlassian',
    type: 'job',
    domain: 'Web Development',
    description: 'Build highly interactive user interfaces for Jira and Confluence using React and GraphQL. Focus on accessibility and performance at scale.',
    location: 'Remote',
    deadline: '2026-08-05T23:59:59Z',
    stipend: '₹28,00,000/year',
    link: 'https://www.atlassian.com/company/careers/all-jobs',
    skills: ['React', 'TypeScript', 'GraphQL', 'CSS'],
    postedDate: '2026-07-15T09:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Remote frontend role focusing on React and GraphQL for enterprise software.',
    matchScore: 88
  },
  {
    id: 'job-004',
    title: 'Cybersecurity Analyst',
    organization: 'CrowdStrike',
    type: 'job',
    domain: 'Cybersecurity',
    description: 'Monitor threat landscapes and analyze malware. You will be responsible for identifying vulnerabilities and enhancing our security posture.',
    location: 'Pune, India',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '₹22,00,000/year',
    link: 'https://www.crowdstrike.com/careers/',
    skills: ['Network Security', 'Python', 'SIEM', 'Malware Analysis'],
    postedDate: '2026-07-19T14:15:00Z',
    source: 'Indeed',
    featured: false,
    aiSummary: 'Core cybersecurity role involving threat monitoring and malware analysis.',
    matchScore: 74
  },
  {
    id: 'job-005',
    title: 'Data Scientist',
    organization: 'Amazon',
    type: 'job',
    domain: 'Data Science',
    description: 'Leverage massive datasets to build predictive models for supply chain optimization. Experience with big data frameworks is a plus.',
    location: 'Bangalore, India',
    deadline: '2026-08-25T23:59:59Z',
    stipend: '₹30,00,000/year',
    link: 'https://www.amazon.jobs/en/search?base_query=Data+Scientist&loc_query=India',
    skills: ['Python', 'SQL', 'Machine Learning', 'Spark'],
    postedDate: '2026-07-21T11:00:00Z',
    source: 'Direct',
    featured: true,
    aiSummary: 'Data Science position optimizing Amazon supply chain using ML and big data.',
    matchScore: 89
  },
  {
    id: 'job-006',
    title: 'Blockchain Developer',
    organization: 'Polygon Labs',
    type: 'job',
    domain: 'Blockchain',
    description: 'Develop and audit smart contracts for the Polygon ecosystem. Contribute to scaling solutions for Ethereum.',
    location: 'Remote',
    deadline: '2026-08-18T23:59:59Z',
    stipend: '$120,000/year',
    link: 'https://polygon.technology/careers',
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'Rust'],
    postedDate: '2026-07-17T16:45:00Z',
    source: 'Web3Jobs',
    featured: false,
    aiSummary: 'Remote smart contract developer role in the Polygon scaling ecosystem.',
    matchScore: 68
  },
  {
    id: 'job-007',
    title: 'Backend Systems Engineer',
    organization: 'Upstox',
    type: 'job',
    domain: 'FinTech',
    description: 'Build high-frequency trading gateways and ultra-low latency order matching systems handling millions of transactions daily.',
    location: 'Mumbai, India',
    deadline: '2026-08-28T23:59:59Z',
    stipend: '₹26,00,000/year',
    link: 'https://upstox.com/careers/',
    skills: ['Java', 'Kafka', 'Redis', 'Microservices'],
    postedDate: '2026-07-22T09:00:00Z',
    source: 'Naukri',
    featured: true,
    aiSummary: 'High throughput FinTech backend engineering role at Upstox.',
    matchScore: 91
  },
  {
    id: 'job-008',
    title: 'Senior AI Specialist',
    organization: 'Fiverr',
    type: 'job',
    domain: 'Artificial Intelligence',
    description: 'Develop AI matching algorithms and automated gig quality evaluation tools for Fiverr global marketplace platform.',
    location: 'Remote',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '$110,000/year',
    link: 'https://www.fiverr.com/jobs',
    skills: ['Python', 'TensorFlow', 'Recommendation Systems', 'FastAPI'],
    postedDate: '2026-07-21T14:20:00Z',
    source: 'Fiverr Careers',
    featured: false,
    aiSummary: 'Global marketplace AI algorithm developer role at Fiverr.',
    matchScore: 84
  },

  // Internships (10)
  {
    id: 'intern-001',
    title: 'AI Research Intern',
    organization: 'NVIDIA',
    type: 'internship',
    domain: 'Artificial Intelligence',
    description: 'Work alongside world-class AI scientists on GPU-accelerated deep learning algorithms and computer vision models.',
    location: 'Bangalore, India',
    deadline: '2026-08-08T23:59:59Z',
    stipend: '₹80,000/month',
    link: 'https://www.nvidia.com/en-us/about-nvidia/careers/',
    skills: ['CUDA', 'PyTorch', 'Computer Vision', 'C++'],
    postedDate: '2026-07-20T12:00:00Z',
    source: 'Internshala',
    featured: true,
    aiSummary: 'Top-tier research internship at NVIDIA focusing on CUDA acceleration & CV.',
    matchScore: 96
  },
  {
    id: 'intern-002',
    title: 'Full Stack Intern',
    organization: 'Zepto',
    type: 'internship',
    domain: 'Web Development',
    description: 'Help build high-speed delivery dispatch platforms using Next.js, Node.js, and Redis.',
    location: 'Mumbai, India',
    deadline: '2026-08-12T23:59:59Z',
    stipend: '₹40,000/month',
    link: 'https://internshala.com/internships/keywords-full-stack-development/',
    skills: ['React', 'Node.js', 'MongoDB', 'Redis'],
    postedDate: '2026-07-22T08:00:00Z',
    source: 'Internshala',
    featured: true,
    aiSummary: 'Fast-paced startup internship at Zepto for full-stack Node/React developers.',
    matchScore: 90
  },
  {
    id: 'intern-003',
    title: 'Data Analytics Intern',
    organization: 'Swiggy',
    type: 'internship',
    domain: 'Data Science',
    description: 'Analyze consumer ordering patterns and build dashboards for growth optimization using SQL and Tableau.',
    location: 'Bangalore, India',
    deadline: '2026-08-15T23:59:59Z',
    stipend: '₹35,000/month',
    link: 'https://careers.swiggy.com/',
    skills: ['SQL', 'Python', 'Tableau', 'Excel'],
    postedDate: '2026-07-21T10:00:00Z',
    source: 'LinkedIn',
    featured: false,
    aiSummary: 'Growth-focused data analytics internship at Swiggy.',
    matchScore: 82
  },

  // Hackathons (8)
  {
    id: 'hack-001',
    title: 'Space Apps Challenge 2026',
    organization: 'NASA x ISRO',
    type: 'hackathon',
    domain: 'Multiple Domains',
    description: 'The world’s largest space & earth science hackathon. Solve real challenges using open data from NASA and ISRO.',
    location: 'Remote & Local Centers',
    mapQuery: 'ISRO Satellite Centre, Bangalore',
    deadline: '2026-09-01T23:59:59Z',
    stipend: 'Global Recognition & Swag',
    link: 'https://devfolio.co/hackathons',
    skills: ['Python', 'GIS', 'Data Analysis', 'Web Dev'],
    postedDate: '2026-07-15T00:00:00Z',
    source: 'Devfolio',
    featured: true,
    aiSummary: 'Global flagship NASA & ISRO hackathon open to students worldwide.',
    matchScore: 85
  },
  {
    id: 'hack-002',
    title: 'GenAI Buildathon India',
    organization: 'Hugging Face x Google Cloud',
    type: 'hackathon',
    domain: 'Artificial Intelligence',
    description: 'Build innovative generative AI applications using Gemini API and Hugging Face Transformers.',
    location: 'IIT Delhi Campus & Online',
    mapQuery: 'IIT Delhi, Hauz Khas, New Delhi',
    deadline: '2026-08-20T23:59:59Z',
    stipend: '$10,000 prize pool',
    link: 'https://unstop.com/hackathons',
    skills: ['Gemini API', 'LangChain', 'Python', 'React'],
    postedDate: '2026-07-20T00:00:00Z',
    source: 'Unstop',
    featured: true,
    aiSummary: 'Generative AI buildathon with $10K prize pool and Google mentor support.',
    matchScore: 98
  },
  {
    id: 'hack-003',
    title: 'ETHIndia 2026',
    organization: 'Devfolio',
    type: 'hackathon',
    domain: 'Blockchain',
    description: 'Asia’s biggest Ethereum hackathon. Build decentralized apps, ZK rollups, and Web3 infrastructure.',
    location: 'KTPO, Whitefield, Bangalore',
    mapQuery: 'KTPO Trade Center, Whitefield, Bangalore',
    deadline: '2026-11-15T23:59:59Z',
    stipend: '$50,000+ in bounties',
    link: 'https://ethindia.co/',
    skills: ['Solidity', 'EVM', 'React', 'IPFS'],
    postedDate: '2026-07-10T00:00:00Z',
    source: 'Devfolio',
    featured: true,
    aiSummary: 'Asia’s premier Web3 hackathon with massive bounty pool.',
    matchScore: 78
  },

  // Research Funding (6)
  {
    id: 'res-001',
    title: 'CSIR Junior Research Fellowship 2026',
    organization: 'CSIR India',
    type: 'research',
    domain: 'Computer Science & AI',
    description: 'Prestigious national fellowship for conducting research in AI, Quantum Computing, and Advanced Cyber-Physical Systems.',
    location: 'New Delhi, India',
    deadline: '2026-08-30T23:59:59Z',
    stipend: '₹37,000/month + HRA',
    link: 'https://csirhrdg.res.in/',
    skills: ['Research Methodology', 'Python', 'Mathematics'],
    postedDate: '2026-07-01T00:00:00Z',
    source: 'Government Portal',
    featured: true,
    aiSummary: 'Government-funded research fellowship for CS research scholars in India.',
    matchScore: 91
  },
  {
    id: 'res-002',
    title: 'Google PhD Fellowship 2026',
    organization: 'Google Research',
    type: 'research',
    domain: 'Artificial Intelligence',
    description: 'Recognizes outstanding graduate students doing exceptional research in computer science and related fields.',
    location: 'Global',
    deadline: '2026-09-15T23:59:59Z',
    stipend: '$50,000 tuition & stipend',
    link: 'https://research.google/outreach/phd-fellowship/',
    skills: ['Deep Learning', 'Publications', 'Algorithms'],
    postedDate: '2026-07-05T00:00:00Z',
    source: 'Google Direct',
    featured: true,
    aiSummary: 'Highly prestigious global fellowship for PhD researchers at Google.',
    matchScore: 94
  }
];

export const stats = {
  totalOpportunities: 2458,
  newToday: 142,
  expiringSoon: 37,
  profileMatch: 95
};

export const aiQuickPrompts = [
  'Show internships matching Python and AI',
  'Find hackathons near me with prize pools',
  'Build my ATS resume for Amazon Data Scientist',
  'What are the 24/7 hiring trends for React Developers?',
  'Help me prep for Google Core Systems interview'
];

export const userProfile = {
  name: 'Alex Chen',
  email: 'alex.chen@university.edu',
  university: 'Indian Institute of Technology, Delhi',
  graduationYear: '2026',
  skills: ['Python', 'Machine Learning', 'React', 'Node.js', 'TensorFlow', 'SQL'],
  interests: ['Artificial Intelligence', 'Web Development', 'Data Science'],
};

